project:
  type: website

website:
  title: "Nina's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: journal
    css: styles.css

execute:
  freeze: auto


